name: compile joss tex

on:
  push:
    branches:
    - joss-submission-do-not-delete
  workflow_dispatch:
    branches:
    - joss-submission-do-not-delete

jobs:
  paper:
    runs-on: ubuntu-latest
    name: Paper Draft
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: TeX and PDF
        uses: docker://openjournals/paperdraft:latest
        with:
          args: '-k paper/paper.md'
        env:
          GIT_SHA: $GITHUB_SHA
          JOURNAL: joss
      - name: Upload
        uses: actions/upload-artifact@v1
        with:
          name: paper
          path: paper/
